dbtcicdnew:
  outputs:
    dev:
      dbname: dev
      host: lin-test.139260835254.us-east-2.redshift-serverless.amazonaws.com
      password: 
      port: 5439
      schema: public
      threads: 1
      type: redshift
      user: admin
  target: dev
